---
- name: (RedHat) Gather services facts
  service_facts:

- name: (RedHat) Ensure firewalld is stopped and service is masked
  systemd:
    service: firewalld
    state: stopped
    enabled: no
    masked: yes
  when: services['firewalld.service'] is defined

- name: (RedHat) Install NFTables package
  yum:
    name: nftables
    state: installed
  register: nftables_install_status

- name: (RedHat) Remove default ruleset files after installation
  file:
    path: /etc/nftables
    state: absent
  when: (nftables_install_status is changed) or (nftables_ruleset is not defined) or ((nftables_ruleset.tables | default([])) == [])
  notify: reload nftables

- name: (RedHat) Ensure NFTables conf dir is present
  file:
    path: /etc/nftables
    state: directory
    owner: root
    group: root
    mode: 0750
