---
- name: (RedHat) Load distro specific variables
  # include_vars: "{{ item }}"
  include_vars: "RedHat.yml"
  # ignore_errors: yes
  when:
    - ansible_os_family == 'RedHat'
    - ansible_distribution != 'Fedora'
  # with_first_found:
  #   - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
  #   - "{{ ansible_os_family | lower }}.yml"

- name: (Debian) Load distro specific variables
  # include_vars: "{{ item }}"
  include_vars: "Debian.yml"
  # ignore_errors: yes
  when:
    - ansible_distribution == 'Debian'
  # with_first_found:
  #   - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
  #   - "{{ ansible_distribution | lower }}.yml"

- set_fact:
    nftables_service: "{{ _nftables_service }}"

- set_fact:
    nftables_ruleset_file: "{{ _nftables_ruleset_file }}"
