---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: "${MOLECULE_VAGRANT_PROVIDER:-libvirt}"
  cachier: none

platforms:
  - name: centos7
    box: centos/7
    cpus: "${MOLECULE_VAGRANT_VM_CPUS:-1}"
    memory: "${MOLECULE_VAGRANT_VM_MEM:-1024}"
  - name: centos8
    box: centos/8
    cpus: "${MOLECULE_VAGRANT_VM_CPUS:-1}"
    memory: "${MOLECULE_VAGRANT_VM_MEM:-1024}"
  - name: debian10
    box: generic/debian10
    cpus: "${MOLECULE_VAGRANT_VM_CPUS:-1}"
    memory: "${MOLECULE_VAGRANT_VM_MEM:-1024}"
  - name: debian11
    box: generic/debian11
    cpus: "${MOLECULE_VAGRANT_VM_CPUS:-1}"
    memory: "${MOLECULE_VAGRANT_VM_MEM:-1024}"

provisioner:
  name: ansible
verifier:
  name: ansible
  enabled: False
lint: |
  yamllint .
